### ISSUE TITLE
build is failing

### ISSUE THREAD

**Issue by pfrgit** [Lakhankumawat/meditation_app_ui#5]
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
lib/src/screens/player_screen/components/body.dart:5:8: Error: Error when reading 'lib/src/screens/player_screen/components/playingDetails.dart': The system cannot find the file specified.

import 'package:meditation_app/src/screens/player_screen/components/playingDetails.dart';
       ^
lib/src/screens/player_screen/components/body.dart:77:22: Error: The method 'PlayingDetails' isn't defined for the class 'Body'.
 - 'Body' is from 'package:meditation_app/src/screens/player_screen/components/body.dart' ('lib/src/screens/player_screen/components/body.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PlayingDetails'.
              child: PlayingDetails()),
                     ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

**Comment by Lakhankumawat** [comment]
Hi @pfrgit  thanks for pointing the issue , hopefully it is resolved now , you can fetch upstream and can start commiting ...
